from python:3.12-slim

run apt-get update \
    && apt-get install -y gnupg curl wget sudo build-essential cmake git libjson-c-dev libwebsockets-dev net-tools jq ripgrep fzf tmux xclip unzip

run git clone https://github.com/tsl0922/ttyd.git \
    && cd ttyd \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install
    
copy requirements.txt requirements.txt
run pip install -r requirements.txt

run curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - \
    && apt-get install -y nodejs \
    && npm install -g inliner \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

env OPENCODE_INSTALL_DIR=/bin
run curl -fsSL https://opencode.ai/install | bash

workdir /workspace
copy main.py main.py
copy agent agent
copy .tmux.conf .tmux.conf
copy mcps mcps

expose 7681

cmd ["python", "main.py"]