from python:3.12-slim

run apt-get update \
    && apt-get install -y gnupg curl wget sudo build-essential cmake git libjson-c-dev libwebsockets-dev net-tools jq ripgrep fzf unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

copy requirements.txt requirements.txt
run pip install -r requirements.txt

env OPENCODE_INSTALL_DIR=/bin
run curl -fsSL https://opencode.ai/install | VERSION=0.5.7 bash

